# Generated by Django 4.2.8 on 2024-07-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_nooriofflinestore_noorionlinestore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nooriofflinestore',
            name='phone',
        ),
    ]
