# Generated by Django 4.2.8 on 2024-08-01 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
    ]
